# Generated by Django 4.0.5 on 2022-07-07 21:20

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_tag_id_alter_taggeditem_content_type_and_more'),
        ('blog', '0002_alter_post_managers_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit'
                                                                                                       '.TaggedItem',
                                                  to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
